name: Deploy Multiple Allure Reports to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest
        shell: bash

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Allure Commandline
        run: |
          curl -o allure-2.22.1.tgz -OL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.1/allure-commandline-2.22.1.tgz
          sudo tar -zxvf allure-2.22.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.22.1/bin/allure /usr/bin/allure
          allure --version
        shell: bash

      # Generate first report
      - name: Run tests and generate first Allure report
        run: |
          pytest --alluredir=allure-results-1
          allure generate allure-results-1 --clean -o allure-report-1
        shell: bash

      # Generate second report
      - name: Run tests and generate second Allure report
        run: |
          pytest --alluredir=allure-results-2
          allure generate allure-results-2 --clean -o allure-report-2
        shell: bash

      # Combine reports into a single directory structure
      - name: Prepare reports for publishing
        run: |
          mkdir -p gh-pages
          mv allure-report-1 gh-pages/report1
          mv allure-report-2 gh-pages/report2
          
          # Create an index.html file to link to both reports
          cat > gh-pages/index.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <title>Test Reports</title>
              <style>
                body { 
                  font-family: Arial, sans-serif;
                  max-width: 800px;
                  margin: 40px auto;
                  padding: 20px;
                  line-height: 1.6;
                }
                h1 { color: #333; }
                .report-link {
                  display: block;
                  margin: 20px 0;
                  padding: 15px;
                  background-color: #f5f5f5;
                  border-radius: 5px;
                  text-decoration: none;
                  color: #333;
                }
                .report-link:hover {
                  background-color: #e5e5e5;
                }
              </style>
            </head>
            <body>
              <h1>Test Reports</h1>
              <a class="report-link" href="./report1">Report 1 - First Test Suite</a>
              <a class="report-link" href="./report2">Report 2 - Second Test Suite</a>
            </body>
          </html>
          EOF
        shell: bash

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages