name: Deploy Allure Report to GitHub Pages

on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:  # Allow manual trigger of the workflow from the GitHub UI.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Using an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies
        shell: bash

#      - name: Install Homebrew
#        run: |
#          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#          echo "export PATH=$HOME/.linuxbrew/bin:$PATH" >> $GITHUB_ENV
#        shell: bash

#      - name: Install Allure Commandline via Homebrew
#        run: |
#          brew install allure  # Install Allure via Homebrew
#        shell: bash
      - name: Install Allure Commandline manually
        run: |
          # Download Allure from GitHub releases
          curl -sSL https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.zip -o allure.zip
          unzip allure.zip -d allure
          sudo mv allure /opt/allure  # Move Allure to /opt for global use
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure  # Create a symbolic link to the allure binary
        shell: bash

      - name: Add allure path
        run: |
          echo "export PATH=/opt/allure/bin:$PATH" >> $GITHUB_ENV  # Add Allure to the PATH
        shell: bash

      - name: Run tests and generate Allure report
        run: |
          pytest --alluredir=allure-results  # Run tests and generate Allure results
          allure generate allure-results --clean -o allure-report  # Generate the Allure report
        shell: bash

      - name: Deploy to GitHub Pages using peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: allure-report
          target_branch: gh-pages
