name: Deploy Allure Report to GitHub Pages

on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest  # Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # PowerShell command
        shell: pwsh  # PowerShell shell on Windows runner.

      - name: Install Allure Commandline
        run: |
          choco install allure  # PowerShell command to install Allure via Chocolatey package manager.
        shell: pwsh  # PowerShell shell on Windows runner.

      - name: Run tests and generate Allure report
        run: |
          pytest --alluredir=allure-results  # PowerShell command to run tests.
          allure generate allure-results --clean -o allure-report  # PowerShell command to generate the Allure report.
        shell: pwsh  # PowerShell shell on Windows runner.
#
#      - name: Deploy to GitHub Pages using peaceiris/actions-gh-pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          folder: allure-report
#          target_branch: gh-pages
